
project_id = "pwwcvslwczyyhejbxevp"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54320
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[functions.linkedin-auth]
verify_jwt = false

[functions.linkedin-posts]
verify_jwt = false
