// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zleurrkvejnitpxftyfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsZXVycmt2ZWpuaXRweGZ0eWZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjU0MTAsImV4cCI6MjA2NTUwMTQxMH0.7NtYbxBu1d9jW64TZjD06kMN7uWbRT7okHGR_9phd_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);